CREATE DATABASE QL_SINHVIEN;
GO

USE QL_SINHVIEN;
GO

CREATE TABLE STUDENTS (
	[IdStudent] NVARCHAR(50) PRIMARY KEY
  , [Name] NVARCHAR(50)
  , [Email] NVARCHAR(50)
  , [Phone] VARCHAR(10)
  , [Gender] BIT
  , [Address] NVARCHAR(100)
  , [Avatar] NVARCHAR(100)
)

GO

CREATE TABLE SCORES (
	[IdStudent] NVARCHAR(50) PRIMARY KEY
  , [English] INT
  , [Computer] INT
  , [Physical] INT
)

GO

CREATE TABLE USERS (
	[username] NVARCHAR(50) PRIMARY KEY
  , [password] NVARCHAR(255)
  , [roleid] INT
)

GO

CREATE TABLE ROLES (
	[roleid] INT PRIMARY KEY
  , [rolename] NVARCHAR(50)
)

ALTER TABLE SCORES
ADD CONSTRAINT FK_IdStudent_STUDENTS
FOREIGN KEY (IdStudent) REFERENCES STUDENTS(IdStudent)

ALTER TABLE USERS
ADD CONSTRAINT FK_roleid_ROLES
FOREIGN KEY (roleid) REFERENCES ROLES(roleid)

